from __future__ import annotations

DOMAIN_ALIAS = {
    'architecture': 'reporting',
    'backend_llm': 'backend_llm',
    'bundle': 'integration',
    'component_descriptors': 'descriptors',
    'component_graph': 'descriptors',
    'component_scoring': 'scoring',
    'component_selection': 'scoring',
    'component_qa': 'orchestrator',
    'contract': 'scoring',
    'history': 'analysis',
    'hotspot': 'analysis',
    'hippo': 'integration',
    'llm_support': 'support',
    'orchestrator': 'orchestrator',
    'paths': 'integration',
    'report': 'reporting',
    'resource': 'integration',
    'scoring': 'scoring',
    'viz': 'reporting',
}

GROUP_PREFIXES = [
    ('backend_llm', 'backend_llm'),
    ('analysis_runner', 'analysis_runner'),
    ('architecture_report', 'architecture_report'),
    ('component_descriptors', 'component_descriptors'),
    ('component_scoring', 'component_scoring'),
    ('component_selection', 'component_scoring'),
    ('component_graph', 'component_descriptors'),
    ('component_qa', 'component_qa'),
    ('feature_advisor', 'feature'),
    ('feature_query', 'feature'),
    ('history_analyzer', 'history_analyzer'),
    ('hotspot_digest', 'hotspot_digest'),
    ('orchestrator', 'orchestrator'),
    ('scoring_policy', 'scoring_policy'),
    ('viz_generator', 'viz_generator'),
    ('hippo', 'hippo'),
    ('bundle_loader', 'bundle_loader'),
    ('report_markdown', 'report_markdown'),
    ('resource_paths', 'resource_paths'),
    ('refresh_decider', 'refresh_decider'),
    ('llm_preflight', 'llm_support'),
    ('llm_guard', 'llm_support'),
]

FILE_FOLDER_HINTS = {
    'analysis_cache': 'analysis',
    'analysis_runner': 'analysis',
    'architecture_report': 'reporting',
    'backend_llm': 'backend_llm',
    'bundle_loader': 'integration',
    'component_descriptors': 'descriptors',
    'component_graph': 'descriptors',
    'component_qa': 'orchestrator',
    'component_scoring': 'scoring',
    'component_selection': 'scoring',
    'contract_engine': 'scoring',
    'feature_advisor': 'feature',
    'feature_query': 'feature',
    'hippo': 'integration',
    'history_analyzer': 'analysis',
    'hotspot_digest': 'analysis',
    'io_utils': 'support',
    'llm_guard': 'support',
    'llm_preflight': 'support',
    'orchestrator': 'orchestrator',
    'paths': 'integration',
    'refresh_decider': 'support',
    'report_markdown': 'reporting',
    'resource_paths': 'integration',
    'scoring_policy': 'scoring',
    'viz_generator': 'reporting',
}

PREFERRED_FOLDER_ALTERNATIVES = {
    'backend_llm': ('backend_llm', ['backend_llm', 'backend']),
    'scoring_policy': ('scoring', ['scoring', 'policy']),
    'analysis_runner': ('analysis', ['analysis', 'runner']),
    'architecture_report': ('reporting', ['reporting', 'architecture_report']),
    'component_descriptors': ('descriptors', ['descriptors', 'component_descriptors']),
    'component_scoring': ('scoring', ['scoring', 'component_scoring']),
    'component_qa': ('orchestrator', ['orchestrator', 'qa']),
    'llm': ('support', ['support', 'llm_support']),
    'llm_support': ('support', ['support', 'llm_support']),
    'refresh': ('support', ['support', 'refresh']),
    'bundle_loader': ('integration', ['integration', 'bundle']),
    'report_markdown': ('reporting', ['reporting', 'report']),
    'paths': ('integration', ['integration', 'paths']),
    'resource_paths': ('integration', ['integration', 'resource']),
    'hippo': ('integration', ['integration', 'hippo']),
    'feature': ('feature', ['feature']),
    'history_analyzer': ('analysis', ['analysis', 'history']),
    'hotspot_digest': ('analysis', ['analysis', 'hotspot']),
    'viz_generator': ('reporting', ['reporting', 'viz']),
}

TERM_FOLDER_RULES = [
    ({'report', 'markdown', 'render'}, 'reporting', ['reporting', 'report'], 0.7),
    ({'hippo', 'bundle', 'resource'}, 'integration', ['integration', 'platform'], 0.68),
]

TERM_GENERIC = {
    'architec',
    'component',
    'module',
    'system',
    'helper',
    'helpers',
    'core',
    'common',
    'shared',
    'misc',
    'utils',
    'python',
    'file',
    'files',
}
