from __future__ import annotations

from pathlib import Path


ARCHITEC_DIR = Path('.architec')
ANALYSIS_JSON_PATH = ARCHITEC_DIR / 'architec-analysis.json'
SUMMARY_MD_PATH = ARCHITEC_DIR / 'architec-summary.md'
VIZ_HTML_PATH = ARCHITEC_DIR / 'architec-viz.html'
ANALYSIS_CACHE_DIR = ARCHITEC_DIR / 'cache' / 'analysis'
BACKEND_LLM_CACHE_PATH = ARCHITEC_DIR / 'cache' / 'backend-llm.json'
REFRESH_STATE_PATH = ARCHITEC_DIR / 'architec-refresh-state.json'
HISTORY_REPORT_PATH = ARCHITEC_DIR / 'architec-history-report.json'
DEBT_LEDGER_PATH = ARCHITEC_DIR / 'architec-debt-ledger.json'
FEATURE_REPORT_PATH = ARCHITEC_DIR / 'architec-feature-suggestion.json'
SCORE_REPORT_PATH = ARCHITEC_DIR / 'architec-component-score.json'
REGISTRY_PATH = ARCHITEC_DIR / 'architec-component-registry.json'
QA_REPORT_PATH = ARCHITEC_DIR / 'architec-component-qa.json'
HOTSPOT_DIGEST_PATH = ARCHITEC_DIR / 'architec-hotspots-topk.json'
COMPONENT_DESCRIPTOR_PATH = ARCHITEC_DIR / 'architec-component-descriptors.json'
ARCHITECTURE_REPORT_MD_PATH = ARCHITEC_DIR / 'architec-architecture-report.md'
TOPOLOGY_REVIEW_PATH = ARCHITEC_DIR / 'architec-topology-review.json'
CLEANUP_INVENTORY_PATH = ARCHITEC_DIR / 'architec-cleanup-inventory.json'
CLEANUP_LEDGER_PATH = ARCHITEC_DIR / 'architec-cleanup-ledger.json'
CLEANUP_SUMMARY_MD_PATH = ARCHITEC_DIR / 'architec-cleanup-summary.md'
ARCHIVE_CANDIDATES_PATH = ARCHITEC_DIR / 'architec-archive-candidates.json'
ARCHIVE_SUMMARY_MD_PATH = ARCHITEC_DIR / 'architec-archive-summary.md'
SEMANTIC_JUDGE_JSON_PATH = ARCHITEC_DIR / 'architec-semantic-judge.json'
SEMANTIC_JUDGE_SUMMARY_MD_PATH = ARCHITEC_DIR / 'architec-semantic-judge-summary.md'
AUTOFIX_PLAN_JSON_PATH = ARCHITEC_DIR / 'architec-autofix-plan.json'
AUTOFIX_SUMMARY_MD_PATH = ARCHITEC_DIR / 'architec-autofix-summary.md'
BASELINE_JSON_PATH = ARCHITEC_DIR / 'architec-baseline.json'
BASELINE_SUMMARY_MD_PATH = ARCHITEC_DIR / 'architec-baseline-summary.md'
GATE_JSON_PATH = ARCHITEC_DIR / 'architec-gate.json'
GATE_SUMMARY_MD_PATH = ARCHITEC_DIR / 'architec-gate-summary.md'
